### ISSUE TITLE
A couple of issues I found!

### ISSUE THREAD

**Issue by discoli** [muhammadmuzzammil1998/BitcoinBot#11]
1) If you run the bot on a different bot than the actual one it's hosted on, since the token is hardcoded in that'll not work, as seen here "<@388984248062967819>", what I suggest doing is replacing it with a member instance of the bot user so then you can do m.Mention(), this will also account for the second issue.

2) When a user has a nickname an exclamation mark is added as a prefix so "<@388984248062967819>" becomes "<@!388984248062967819>" or something along those lines, therefore using the thing above it could be repaired easily, you can use https://godoc.org/github.com/bwmarrin/discordgo#Session.GuildMember that function there, to get the current but user with s.State.User.ID, this would make it even nicer.

3) Make it so that this code ```if strings.Split(message, " ")[1] == "help" {``` also makes it so that the message is turned to lowercase so that typing >btc hElp would still work.

**Comment by muhammadmuzzammil1998** [comment]
Thank you @discoli 
1) The m.Mention() you were talking about is [this one right](https://godoc.org/github.com/bwmarrin/discordgo#User.Mention)?

2) Thanks for this. Didn't know about it.

3) Got it! 😄

**Comment by discoli** [comment]
@muhammadmuzzammil1998 Yup, it is m.Mention(), this will get the string to mention a user.

No problem.
