### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by drstevebrulemd** [muhammadmuzzammil1998/BitcoinBot#17]
Error
Invalid response: 400 Bad Request
Report
https://bit.ly/btcBotReport
Email
bitcoinbot@muzzammil.xyz

**Comment by muhammadmuzzammil1998** [comment]
What command did you use?

**Comment by muhammadmuzzammil1998** [comment]
Waiting for response. The issue will be closed if no response is given within a week from now.
